name: "kana"
title: "Kana"
base: core18
version: "0.0.1.2"
contact: "https://kana.renorari.net/support/"
issues: "https://github.com/TarochanChannel/Kana-Client/issues"
source-code: "https://github.com/TarochanChannel/Kana-Client.git"
website: "https://kana.renorari.net/"
summary: "あなたのアシスタントのKanaがあなたへお手伝いをします。"
description: |
    __Kana-Client__
    あなたのアシスタントのKanaがあなたへお手伝いをします。
confinement: strict
icon: "snap/gui/icon.png"
license: "Apache-2.0"
grade: stable

architectures:
    - build-on: arm64
    - build-on: armhf
    - build-on: amd64
    - build-on: i386

apps:
    kana:
        command: $SNAP/app/kana-client --no-sandbox
        extensions: [gnome-3-28]
        plugs:
            - browser-support
            - network
            - network-bind
        environment:
            TMPDIR: $XDG_RUNTIME_DIR

parts:
    kana:
        plugin: nil
        source: app/
        override-build: |
            export ELECTRON_GET_USE_PROXY=1
            export GLOBAL_AGENT_HTTP_PROXY="${http_proxy}"
            export GLOBAL_AGENT_HTTPS_PROXY="${http_proxy}"
            npm i
            npx electron-builder -l --dir
            cp -rv dist/linux-* $SNAPCRAFT_PART_INSTALL/app
        build-snaps:
            - node/14/stable
        build-packages:
            - unzip
        stage-packages:
            - libnss3
            - libnspr4
