name: kana
title: "Kana"
base: core18
version: "0.0.1"
license: "Apache License 2.0"
summary: KanaのElectronクライアントアプリ
description: |
    Kana-Client
    KanaのElectronクライアントアプリ
icon: "icon.svg"
grade: stable
confinement: strict

apps:
    kana:
        command: "kana/Kana Client --no-sandbox"
        extensions: [gnome-3-34]
        plugs:
            - browser-support
            - network
            - network-bind
        environment:
            TMPDIR: $XDG_RUNTIME_DIR

parts:
    kana:
        plugin: nil
        source: app/
        override-build: |
            export ELECTRON_GET_USE_PROXY=1
            export GLOBAL_AGENT_HTTP_PROXY="${http_proxy}"
            export GLOBAL_AGENT_HTTPS_PROXY="${http_proxy}"
            npm install
            npm run build
            cp -rv dist/linux-* $SNAPCRAFT_PART_INSTALL/kana
        build-snaps:
            - node/14/stable
        build-packages:
            - unzip
        stage-packages:
            - libnss3
            - libnspr4
